"""
gen_parity_vectors.py — freeze the Python spec's answers on the full case set
(50 eval cases + 12 golden patterns) into docs/parity_vectors.js, so the JS
port that powers the hostable page can be mechanically held to the Python
spec. The page runs this comparison on load and shows the result; there is no
"trust me" between the two implementations.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from collabproof import Collab, Q, assess
from run_eval import build_cases
from collabproof.spec import Brand, Creator, EntityType, TaxBearer, rup

COMPANY = Brand(EntityType.COMPANY)
SMALL_INDIVIDUAL = Brand(EntityType.INDIVIDUAL,
                         preceding_fy_profession_receipts_paise=rup(40_00_000))


def golden_cases():
    C = Creator
    return [
        Collab(brand=COMPANY, creator=C(), product_fmv_paise=rup(30_000)),
        Collab(brand=COMPANY, creator=C(), product_fmv_paise=rup(15_000)),
        Collab(brand=COMPANY, creator=C(fy_prior_benefits_from_brand_paise=rup(10_000)),
               product_fmv_paise=rup(15_000)),
        Collab(brand=COMPANY, creator=C(), product_fmv_paise=rup(30_000),
               product_retained=False),
        Collab(brand=SMALL_INDIVIDUAL, creator=C(), product_fmv_paise=rup(30_000)),
        Collab(brand=COMPANY, creator=C(pan_furnished=False), product_fmv_paise=rup(30_000)),
        Collab(brand=COMPANY, creator=C(), cash_fee_paise=rup(50_000),
               product_fmv_paise=rup(25_000)),
        Collab(brand=COMPANY, creator=C(), product_fmv_paise=rup(27_000),
               tax_borne_by=TaxBearer.PROVIDER),
        Collab(brand=COMPANY, creator=C(gst_registered=True,
                                        fy_prior_aggregate_turnover_paise=rup(19_50_000)),
               cash_fee_paise=rup(50_000), product_fmv_paise=rup(60_000)),
        Collab(brand=COMPANY, creator=C(special_category_state=True,
                                        fy_prior_aggregate_turnover_paise=rup(10_00_000)),
               cash_fee_paise=rup(30_000), product_fmv_paise=rup(20_000)),
        Collab(brand=COMPANY, creator=C(is_resident=False), product_fmv_paise=rup(30_000)),
        Collab(brand=Brand(EntityType.COMPANY, in_business=False), creator=C(),
               product_fmv_paise=rup(30_000)),
    ]


def facts_of(c: Collab) -> dict:
    return {
        "brand_entity": c.brand.entity_type.value,
        "brand_business_turnover": c.brand.preceding_fy_business_turnover_paise,
        "brand_profession_receipts": c.brand.preceding_fy_profession_receipts_paise,
        "brand_in_business": c.brand.in_business,
        "resident": c.creator.is_resident,
        "pan": c.creator.pan_furnished,
        "special_state": c.creator.special_category_state,
        "gst_registered": c.creator.gst_registered,
        "prior_benefits": c.creator.fy_prior_benefits_from_brand_paise,
        "prior_194r_tds": c.creator.fy_prior_194r_tds_paise,
        "prior_cash_fees": c.creator.fy_prior_cash_fees_from_brand_paise,
        "prior_cash_tds": c.creator.fy_prior_cash_tds_paise,
        "prior_turnover": c.creator.fy_prior_aggregate_turnover_paise,
        "cash": c.cash_fee_paise,
        "product": c.product_fmv_paise,
        "retained": c.product_retained,
        "deliverable_linked": c.deliverable_linked,
        "bearer": c.tax_borne_by.value,
    }


def expected_of(c: Collab) -> dict:
    a = assess(c)
    if not a.ok:
        return {"ok": False, "refusal": a.refusal_rule_id}
    return {
        "ok": True,
        "tds_194r": a.d(Q.TDS_194R),
        "aggregate": a.d(Q.AGGREGATE_BENEFIT),
        "gate": a.d(Q.RELEASE_GATE),
        "fork": {b.basis_rule_id: b.tds_paise for b in a.cash_tds_fork},
        "fork_material": a.fork_material,
        "gst_supply": a.d(Q.GST_SUPPLY_VALUE),
        "gst_turnover_after": a.d(Q.GST_TURNOVER_AFTER),
        "gst_reg": a.d(Q.GST_REG_REQUIRED),
        "gst_liability": a.d(Q.GST_LIABILITY),
    }


def main():
    cases = build_cases() + golden_cases()
    vectors = [{"facts": facts_of(c), "expected": expected_of(c)} for c in cases]
    os.makedirs(os.path.join(os.path.dirname(__file__), "docs"), exist_ok=True)
    out = os.path.join(os.path.dirname(__file__), "docs", "parity_vectors.js")
    with open(out, "w") as f:
        f.write("// GENERATED by gen_parity_vectors.py — do not edit by hand.\n")
        f.write("// Frozen answers of the Python spec on the full case set; the JS\n")
        f.write("// engine is checked against these on every page load.\n")
        f.write("window.PARITY_VECTORS = ")
        json.dump(vectors, f, indent=1)
        f.write(";\n")
    print(f"wrote {len(vectors)} vectors -> docs/parity_vectors.js")


if __name__ == "__main__":
    main()
